### ISSUE TITLE
Directory name is incorrect

### ISSUE THREAD

**Issue by BojamaV** [tdh8316/Investigo#16]
you used a i instead of an I so it wasn't working

**Comment by tdh8316** [comment]
Hi, thanks for opening the issue!
But unfortunately, I can't get what you mean. May I ask you for a more detailed description?

**Comment by BojamaV** [comment]
When the user does cd investigo it isn't working correctly, its a small bug
but just adjust it to cd Investigo instead

**Comment by tdh8316** [comment]
Thank you for pointing the issue out!
