### ISSUE TITLE
Feature Request: Timeout and retry setting direly needed

### ISSUE THREAD

**Issue by anoduck** [tdh8316/Investigo#17]
I am not fortunate enough to have a stable WAN connection, it is part of life for me. Anytime the connection times out, which is so far every time I have run this script, the process breaks and stops dead in its tracks. I have run the script seven times in a row, and it has crashed every time due to time out errors.

Users need to be able to pass the settings for both timeout rates and connection retries for this script. This should pose no difficulty implementing.

**Comment by tdh8316** [comment]
Yes, you're right. It is not that difficult to implement. I'll add the command-line parameter for time-out, and so on. Thanks!
