### ISSUE TITLE
errors + suggestions

### ISSUE THREAD

**Issue by lucmski** [tdh8316/Investigo#4]
Hi mate,

Hope you are all well !

## In terms of false results: 
```bash
Duolingo: https://www.duolingo.com/snerk7oups
```

## In terms of TOR integration, here are some suggestions:
With Docker/Docker-compose
- https://github.com/dockage/tor-privoxy
- https://github.com/rdsubhas/docker-tor-privoxy-alpine
- https://github.com/u1234x1234/torpool

Code:
- https://www.devdungeon.com/content/making-tor-http-requests-go
- https://github.com/nogoegst/scallion/blob/master/main.go
- https://github.com/gocolly/colly/tree/master/_examples (main could be interesting to use this framework for more accurate matching in the DOM)

Cheers,
L.

**Comment by tdh8316** [comment]
Thanks for your suggestions ❤️ 

Unfortunately, I'm afraid I cannot play with my computer now as I currently have a lot of tasks which I have to because of school life.

I will respond when I have enough time to deal with this issue!

**Comment by lucmski** [comment]
Hi,

I forked Investsigo and added Tor 
https://github.com/lucmski/Investigo/blob/msk/main.go

Also, I added a webui for storing and browsing results

it is still WIP

**Comment by tdh8316** [comment]
Wow, I love it!

If you want and are ready, you can make a PR to merge these changes.
